'use client';
import {useEffect,useRef,useState} from 'react';
import {Landmark,RefreshCw,ArrowUpRight,Search,FileText,ChevronRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import seed from '@/app/data/seed.json';
import DistrictMap from '@/components/district-map';
import MoneyExplorer from '@/components/money-explorer';
import VotingHistory from '@/components/voting-history';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const date=(s:string)=>s?new Date(s).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}):'Not available';
const link=(url:string,label='Original record')=><a href={url} target="_blank" rel="noreferrer">{label} <ArrowUpRight size={14}/></a>;
function Stamp({data}:any){return <p className="stamp">{data?<>Retrieved {date(data.syncedAt)} · {data.year??2026} filing window</>:'Not yet synchronized'}</p>}
export default function Page(){
 const [data,setData]=useState<Record<string,any>>(seed),[query,setQuery]=useState(''),[chamber,setChamber]=useState('All'),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[errors,setErrors]=useState<string[]>([]);
 const lock=useRef(false),cancel=useRef(false),dataRef=useRef(data);dataRef.current=data;
 useEffect(()=>{fetch('/api/data').then(r=>r.json()).then((r:any)=>{setData(r.data);if(!r.persistent)setMessage('Showing the verified starting snapshot. Live storage is unavailable.');}).catch(()=>setMessage('Could not check saved updates. Showing the starting snapshot.'));},[]);
 async function sync(memberId?:string){
  if(lock.current)return {error:'A sync is already running.'};
  if(memberId&&!dataRef.current.roster.members.some((m:any)=>m.id===memberId))throw new Error('Unknown Florida member.');
  lock.current=true;cancel.current=false;setBusy(true);setErrors([]);const failures:string[]=[];let completed=0;
  const jobs:any[]=memberId?[{source:'lobbying',memberId,label:'Lobbyist disclosures'}]:['roster','campaign','financial','travel','votesHouse','votesSenate'].map(source=>({source,label:source==='votesHouse'?'House votes':source==='votesSenate'?'Senate votes':source}));
  try{for(let i=0;i<jobs.length;i++){
   if(cancel.current)break;const job=jobs[i];setMessage(`Syncing ${job.label} · ${i+1} of ${jobs.length}`);
   try{if(job.source.startsWith('votes')){let after:number|undefined;let more=true;while(more&&!cancel.current){const r=await fetch('/api/votes/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chamber:job.source==='votesHouse'?'House':'Senate',after})});const v:any=await r.json();if(!r.ok)throw Error(v.error??'Vote sync failed');more=v.more;after=v.after;setData(old=>({...old,votesRevision:Date.now()}));}completed++;continue;}const r=await fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(job)});const result:any=await r.json();if(!r.ok)throw new Error(result.error??'Source unavailable');setData(old=>({...old,[result.key]:result.value}));completed++;if(job.source==='roster')dataRef.current={...dataRef.current,roster:result.value};}
   catch(e){failures.push(`${job.label}: ${e instanceof Error?e.message:'Update failed'}`);setErrors([...failures]);}
   if(!memberId&&i===3)jobs.push(...dataRef.current.roster.members.map((m:any)=>({source:'lobbying',memberId:m.id,label:`LD-203 · ${m.name}`})));
  }}finally{setMessage(`${cancel.current?'Sync stopped':'Sync finished'} · ${completed} sources updated${failures.length?` · ${failures.length} unavailable (previous records kept)`:''}.`);setBusy(false);lock.current=false;}
  return {updated:completed,errors:failures,stopped:cancel.current};
 }
 const syncRef=useRef(sync);syncRef.current=sync;
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'sync_florida_disclosures',title:'Sync Florida disclosures',description:'Fetch and save source records, updating this dashboard. Omit memberId for all sources; provide a bioguide memberId for that member’s lobbyist disclosures.',inputSchema:{type:'object',properties:{memberId:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:any)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>k!=='memberId')||(input.memberId!==undefined&&typeof input.memberId!=='string'))throw new Error('Expected optional memberId string.');return syncRef.current(input.memberId);}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 const members=data.roster.members,visible=members.filter((m:any)=>(chamber==='All'||m.chamber===chamber)&&`${m.name} ${m.party} ${m.district??''}`.toLowerCase().includes(query.toLowerCase()));
 const m=members.find((x:any)=>x.id===selected),fin=m?data.campaign?.records.find((r:any)=>m.fecIds.includes(r.candidateId)):null,lda=m?data['lda:'+m.id]:null;
 const personal=m?data.financial?.records.filter((r:any)=>r.memberId===m.id)??[]:[],travel=m?data.travel?.records.filter((r:any)=>r.memberId===m.id)??[]:[];
 function jumpToDistrict(n:number){setQuery('');setChamber('All');setTimeout(()=>{const el=document.getElementById(`district-${n}`);el?.scrollIntoView({behavior:'smooth',block:'center'});el?.focus({preventScroll:true});history.replaceState(null,'',`#district-${n}`);},50);}
 return <main className="ledger">
  <section className="titlebar"><div><div className="eyebrow">THE FLORIDA DELEGATION</div><h1>Political Parlay</h1><p>Follow the money. Inspect the record.</p></div><div className="syncbox"><Button className="sync" onClick={()=>sync()} disabled={busy}><RefreshCw size={17} className={busy?'spin':''}/>{busy?'Syncing records':'Sync latest records'}</Button><small>Public filings · Full sync takes several minutes</small></div></section>
  {(message||busy)&&<div className="syncstatus" role="status">{message}{busy&&<Button variant="outline" size="sm" onClick={()=>{cancel.current=true;setMessage('Stopping after the current source finishes…');}}>Stop sync</Button>}</div>}
  {!!errors.length&&<details className="errors"><summary>{errors.length} sources could not update</summary>{errors.map(e=><p key={e}>{e}</p>)}</details>}
  <section className="overview"><div><span>Serving members</span><strong>{members.length}</strong></div><div><span>House / Senate</span><strong>{members.filter((m:any)=>m.chamber==='House').length} <i>/</i> {members.filter((m:any)=>m.chamber==='Senate').length}</strong></div><div><span>Campaign finance cycle</span><strong>2025–26</strong></div><div><span>Lobbyist sources checked</span><strong>{members.filter((x:any)=>data['lda:'+x.id]).length} <i>/ {members.length}</i></strong></div></section>
  <DistrictMap members={members} onSelect={jumpToDistrict}/>
  <MoneyExplorer data={data}/>
  <div className="sectionhead"><div><h2>Explore the delegation</h2><p>Open a member to inspect campaign totals, lobbyist filings, finances and travel.</p></div><span className="verified">SOURCE-LINKED RECORDS</span></div>
  <div className="filters"><div className="search"><Search size={18}/><Input aria-label="Search members" placeholder="Search name, party or district" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="chambers" aria-label="Chamber filter">{['All','House','Senate'].map(c=><Button key={c} variant={chamber===c?'default':'outline'} onClick={()=>setChamber(c)} aria-pressed={chamber===c}>{c==='All'?'All members':c}</Button>)}</div><span>{visible.length} members</span></div>
  <div className="party-columns">{['Democratic','Republican'].map(party=><section className={`party-column ${party==='Democratic'?'blue-column':'red-column'}`} key={party}><header><span className="eyebrow">FLORIDA DELEGATION</span><h2>{party==='Democratic'?'Democrats':'Republicans'} <small>{visible.filter((x:any)=>x.party===party).length}</small></h2></header>{visible.filter((x:any)=>x.party===party).sort((a:any,b:any)=>(a.chamber==='Senate'?0:Number(a.district))-(b.chamber==='Senate'?0:Number(b.district))).map((member:any)=>{const f=data.campaign?.records.find((r:any)=>member.fecIds.includes(r.candidateId)),l=data['lda:'+member.id];return <button className="member-row" id={member.chamber==='House'?`district-${member.district}`:member.id} key={member.id} onClick={()=>setSelected(member.id)}><span className="seat-number">{member.chamber==='Senate'?'US':String(member.district).padStart(2,'0')}</span><span className="row-person"><span className="eyebrow">{member.chamber==='Senate'?'U.S. SENATE · STATEWIDE':`HOUSE · DISTRICT ${member.district}`}</span><h3>{member.name}</h3><span className="row-records">{l?`${l.records.length} matched lobbyist records`:'Lobbyist records not yet checked'}</span></span><span className="row-money"><strong>{f?money(f.receipts):'Not available'}</strong><span>Campaign receipts</span><small>{f?`Through ${date(f.coverageEnd)}`:'No matched FEC report'}</small></span><ChevronRight size={16}/></button>})}{!visible.some((x:any)=>x.party===party)&&<p className="party-empty">No members match these filters.</p>}</section>)}</div>
  {!visible.length&&<p className="empty">No members match these filters.</p>}
  {!members.some((m:any)=>m.chamber==='House'&&m.district===20)&&<div className="vacancy" id="district-20" tabIndex={-1}>House District 20 · Vacant <span>{link('https://clerk.house.gov/members/FL20/vacancy','Clerk vacancy record')}</span></div>}
  <section className="method"><h2>Read the record, with context.</h2><div className="methodgrid"><div><h3>Contributions & related payments</h3><p>LD-203 filings identify contributions by registered lobbyists and firms, plus some payments honoring officials. The payee may be a campaign, charity or event—not the member personally. Name matches are not findings of wrongdoing.</p></div><div><h3>What this does not total</h3><p>Campaign receipts, outside spending, lobbying expenses and personal wealth are different measures. They are never added together here. Employer names on individual donations do not make them corporate payments.</p></div><div><h3>Coverage & update limits</h3><p>Sync checks published records; it cannot reveal unreported money. Publication delays and rate limits apply. House documents are indexed; Senate personal disclosures and travel require manual review.</p></div></div><details><summary>Sources and matching methodology</summary><p>{link(data.roster.source,'Congress roster')} · {link(data.roster.mappingSource,'Identifier crosswalk')} · {link('https://www.fec.gov/data/','FEC')} · {link('https://lda.gov/','LDA')} · {link('https://disclosures-clerk.house.gov/','House Clerk')}</p><p>Campaign figures use the 2026 two-year cycle. LD-203 searches use the 2026 filing year, then match first and last names in honoree or payee fields. Aliases can be missed. The latest returned filing per filer and period is used; identical disclosed entries are grouped with all document links retained. Searches are capped at four pages per field and any cap is shown. The breakdown sums grouped observed records, with explicit deduplication and coverage limits; it is not a verified total received by the member. House filings include extensions and amendments; indexing does not mean their contents have been analyzed.</p><Stamp data={data.roster}/></details></section>
  <footer className="sitefooter"><span>POLITICAL PARLAY</span><span>Public records. Visible sources. No influence scores.</span></footer>
  <Sheet open={!!m} onOpenChange={open=>{if(!open)setSelected(null);}}><SheetContent className="detailpanel"><SheetHeader><div className="eyebrow">{m?.chamber} {m?.district?`· DISTRICT ${m.district}`:''} · {m?.party}</div><SheetTitle className="membertitle">{m?.name}</SheetTitle><SheetDescription>Inspect reported money and the documents behind it.</SheetDescription></SheetHeader>{m&&<div className="detailbody"><Tabs defaultValue="overview" key={m.id}><TabsList className="recordtabs"><TabsTrigger value="overview">Breakdown</TabsTrigger><TabsTrigger value="campaign">Campaign</TabsTrigger><TabsTrigger value="lobbying">Lobbyists</TabsTrigger><TabsTrigger value="financial">Finances</TabsTrigger><TabsTrigger value="travel">Travel</TabsTrigger><TabsTrigger value="voting">Votes</TabsTrigger></TabsList>
  <TabsContent value="overview"><MoneyExplorer data={data} member={m}/></TabsContent><TabsContent value="voting"><VotingHistory member={m} revision={data.votesRevision}/></TabsContent><TabsContent value="campaign"><h2>Campaign finance</h2><p>Money reported by the candidate’s authorized committees, for the 2025–26 cycle.</p>{fin?<><div className="bigfigure"><span>Total receipts</span><strong>{money(fin.receipts)}</strong><small>{date(fin.coverageStart)} – {date(fin.coverageEnd)}</small></div><dl className="moneylist">{[['Itemized individual contributions',fin.individualItemized],['Other political committee contributions',fin.committee],['Transfers from authorized committees',fin.transfers],['Total disbursements',fin.spent],['Cash on hand',fin.cash],['Reported debt',fin.debt]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{money(Number(value))}</dd></div>)}</dl><p className="note">These categories are not an exhaustive breakdown of receipts. Cash and debt are balances, not donations. Outside spending is excluded.</p>{link(fin.source,'Explore donors and committee filings at FEC')}</>:<p className="empty">No FEC totals matched to this member.</p>}<Stamp data={data.campaign}/></TabsContent>
  <TabsContent value="lobbying"><div className="sectionhead"><h2>Lobbyist disclosures</h2><Button variant="outline" size="sm" disabled={busy} onClick={()=>sync(m.id)}><RefreshCw size={14}/>Sync member</Button></div><p>LD-203 contributions and related payments naming this member as honoree or payee. Always check the actual recipient.</p><Stamp data={lda}/>{lda?.truncated&&<p className="errors">Partial results: the source page limit was reached.</p>}{!lda?<p className="empty">This member has not yet been checked. Use Sync member.</p>:!lda.records.length?<p className="empty">No records matched this name in the searched filings. This is not proof that no contributions or relationships exist.</p>:<><p className="note">{lda.records.length} grouped records · Duplicate disclosures retain multiple source links. Explore grouped observed amounts in the Breakdown tab.</p>{lda.records.map((r:any)=><article className="record" key={r.id}><div className="recordheading"><strong>{r.contributor||r.registrant}</strong><b>{money(r.amount)}</b></div><p><span className="field">Actual payee</span>{r.payee||'Not specified'}</p>{r.honoree&&<p><span className="field">Honoree</span>{r.honoree}</p>}<p className="note">{r.kind} · {date(r.date)}<br/>Filer: {r.lobbyist||r.registrant}</p><div className="sourcelinks">{r.sources.map((s:string,i:number)=><span key={s}>{link(s,`Filing${r.sources.length>1?' '+(i+1):''}`)}</span>)}</div></article>)}</>}</TabsContent>
  <TabsContent value="financial"><h2>Personal financial disclosures</h2><p>Original disclosures can include assets, outside income, liabilities, gifts and securities transactions. Values have not been extracted or summed.</p>{m.chamber==='Senate'?<div className="empty">Senate records are not automatically indexed here. The official portal requires its own access terms.<p>{link('https://efdsearch.senate.gov/search/home/','Open Senate financial disclosures')}</p></div>:<><Stamp data={data.financial}/>{!personal.length&&<p className="empty">No matching documents in the 2026 House index. This does not establish an absence of reportable interests.</p>}{personal.map((r:any)=><article className="record document" key={r.id}><FileText size={21}/><div><strong>{r.kind}</strong><p className="note">Filed {r.date} · Document {r.id}</p>{link(r.source,'Read disclosure')}</div></article>)}</>}</TabsContent>
  <TabsContent value="travel"><h2>Privately sponsored travel</h2><p>Sponsored trips can identify relationships beyond campaign donations. Staff travel is labeled separately; trip costs remain in the documents.</p>{m.chamber==='Senate'?<div className="empty">Senate travel reports are not automatically indexed.<p>{link('https://www.ethics.senate.gov/public/index.cfm/travel','Senate travel disclosure information')}</p></div>:<><Stamp data={data.travel}/><p className="note">2026 filing index; some trips occurred earlier. Amendments are separate documents.</p>{!travel.length&&<p className="empty">No matching travel documents in the retrieved index.</p>}{travel.map((r:any)=><article className="record" key={r.id}><div className="eyebrow">{r.memberTrip?'MEMBER TRAVEL':'STAFF / OTHER FILER'}</div><h3>{r.destination}</h3><p><span className="field">Sponsor</span>{r.sponsor||'See source document'}</p><p><span className="field">Traveler</span>{r.traveler}</p><p className="note">{r.start} – {r.end} · {r.kind}</p>{link(r.source,'Read travel disclosure')}</article>)}</>}</TabsContent>
  </Tabs></div>}</SheetContent></Sheet>
 </main>;
}

