'use client';
import {useMemo,useState} from 'react';
import {PieChart,Pie,Cell,Tooltip} from 'recharts';
import {ChartContainer} from '@/components/ui/chart';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {campaignRows,lobbyingRows,groupMoney} from '@/lib/money-analysis.mjs';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const colors=['#285d99','#b83c4c','#9c762d','#426f64','#7a5c8d','#52798a','#985b38','#788190'];
function Choice({label,value,onChange,options}:any){return <label className="analysis-choice"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,t]:any)=><SelectItem value={v} key={v}>{t}</SelectItem>)}</SelectContent></Select></label>}
export default function MoneyExplorer({data,member}:any){const [metric,setMetric]=useState(member?'feca':'campaign'),[dimension,setDimension]=useState(member?'contributor':'party'),[party,setParty]=useState('All'),[search,setSearch]=useState(''),[selected,setSelected]=useState<string|null>(null);const members=member?[member]:data.roster.members;
 const all=useMemo(()=>metric==='campaign'?campaignRows(data,members):lobbyingRows(data,members).filter((r:any)=>metric==='lda'||r.type==='feca'),[data,member,metric]);
 const rows=all.filter((r:any)=>(party==='All'||r.members.some((id:string)=>members.find((m:any)=>m.id===id)?.party===party))&&`${r.contributor} ${r.payee} ${r.honorees?.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 const groups=groupMoney(rows,members,dimension),total=groups.reduce((s:number,g:any)=>s+g.value,0),positive=groups.filter((g:any)=>g.value>0),chart=positive.length>8?[...positive.slice(0,7),{name:'Other groups',value:positive.slice(7).reduce((s:number,g:any)=>s+g.value,0)}]:positive;
 const active=groups.find((g:any)=>g.name===selected);const partial=members.filter((m:any)=>data['lda:'+m.id]?.truncated).length;
 function changeMetric(v:string){setMetric(v);setSelected(null);if(v==='campaign'){setDimension(member?'member':'party');setSearch('');}else if(member)setDimension('contributor');}
 return <section className="money-explorer" aria-label={member?'Member money breakdown':'Delegation money breakdown'}><div className="sectionhead"><div><div className="eyebrow">EXPLORE THE MONEY</div><h2>{member?'Who appears in the disclosures?':'Money by party, member and contributor'}</h2></div></div><div className="analysis-controls"><Choice label="Measure" value={metric} onChange={changeMetric} options={[['campaign','Campaign receipts · 2025–26'],['feca','LD-203 political contributions · 2026'],['lda','All LD-203 related payments · 2026']]}/><Choice label="Group by" value={dimension} onChange={(v:string)=>{setDimension(v);setSelected(null);}} options={metric==='campaign'?[['party','Party'],['member','Member']]:[['party','Party'],['member','Member'],['contributor','Named contributor'],['payee','Actual payee'],['registrant','Lobbying registrant / filer']]}/>{!member&&<Choice label="Party filter" value={party} onChange={(v:string)=>{setParty(v);setSelected(null);}} options={[['All','All parties'],['Democratic','Democratic'],['Republican','Republican']]}/>}{metric!=='campaign'&&<label className="analysis-choice"><span>Find contributor or payee</span><Input value={search} onChange={e=>{setSearch(e.target.value);setSelected(null);}} placeholder="For example, BlackRock"/></label>}</div>
 <p className="analysis-context">{metric==='campaign'?'Sum of candidate committee receipts for the 2025–26 cycle. Includes transfers and other receipts, not just donations. Reporting dates vary.':'Sum of observed, grouped LD-203 disclosures—not a verified total received by officials or their campaigns. Check the actual payee. These amounts can overlap FEC totals; never add the two measures.'}</p>{metric!=='campaign'&&<p className="note">{partial?`${partial} member searches reached the source page limit. `:''}Identical date, amount, contributor, payee and payment-type entries are counted once across members. Distinct identical payments may be collapsed; differently worded duplicates may remain. Shared records have their own group. Party groups use the current roster.</p>}
 <div className="analysis-body"><div className="money-chart"><div className="chart-total"><strong>{money(total)}</strong><span>{metric==='campaign'?'Reported receipts in this view':'Observed disclosed amounts in this view'}</span><small>{rows.length} {metric==='campaign'?'candidate reports':'grouped records'}</small></div>{chart.length&&groups.every((g:any)=>g.value>=0)?<ChartContainer config={{value:{label:'Reported amount'}}} className="donut"><PieChart><Pie data={chart} dataKey="value" nameKey="name" innerRadius="58%" outerRadius="85%" paddingAngle={1} onClick={(g:any)=>{if(g.name!=='Other groups')setSelected(g.name);}}>{chart.map((g:any,i:number)=><Cell key={g.name} fill={g.name==='Democratic'?'#285d99':g.name==='Republican'?'#b83c4c':colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(value:any)=>money(Number(value))}/></PieChart></ChartContainer>:<p className="note">{rows.length?'Use the table for zero or negative amounts.':'No records match this view.'}</p>}<ul className="chart-legend">{chart.map((g:any,i:number)=><li key={g.name}><i style={{background:g.name==='Democratic'?'#285d99':g.name==='Republican'?'#b83c4c':colors[i%colors.length]}}/><span>{g.name}</span><b>{total>0?(g.value/total*100).toFixed(1)+'%':'—'}</b></li>)}</ul><p className="note">{chart.length>0?'Largest seven groups plus “Other” when needed. The table shows every group.':''}</p></div><div className="pivot-scroll"><Table><TableHeader><TableRow><TableHead>Group</TableHead><TableHead className="numeric">Amount</TableHead><TableHead className="numeric">Records</TableHead><TableHead className="numeric">Share</TableHead></TableRow></TableHeader><TableBody>{groups.map((g:any)=><TableRow key={g.name} data-selected={selected===g.name}><TableCell><button className="group-drill" onClick={()=>setSelected(selected===g.name?null:g.name)} aria-expanded={selected===g.name}>{g.name}</button></TableCell><TableCell className="numeric">{money(g.value)}</TableCell><TableCell className="numeric">{g.count}</TableCell><TableCell className="numeric">{total>0?(100*g.value/total).toFixed(1)+'%':'—'}</TableCell></TableRow>)}</TableBody></Table></div></div>
 {active&&<div className="money-drill"><h3>{active.name} · {money(active.value)}</h3><p className="note">{active.count} grouped records. Original payees and filing links are preserved below.</p>{active.rows.map((r:any)=><article className="money-evidence" key={r.key}><div><strong>{money(r.amount)}</strong><span>{r.date?.slice(0,10)}</span></div><p><b>{r.contributor}</b><br/>Actual payee: {r.payee||'Not specified'}{r.honorees?.length>0&&<><br/>Named honoree: {r.honorees.join('; ')}</>}</p><div className="sourcelinks">{r.sources.map((url:string,i:number)=><a key={url} href={url} target="_blank" rel="noreferrer">{metric==='campaign'?'FEC report':`Filing ${i+1}`} ↗</a>)}</div></article>)}</div>}
 </section>;
}
