'use client';
import {useEffect,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
const yes=(p:string)=>['Yea','Aye','Yes'].includes(p),no=(p:string)=>['Nay','No'].includes(p);
export default function VotingHistory({member,revision}:any){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[year,setYear]=useState('all'),[topic,setTopic]=useState('all'),[retry,setRetry]=useState(0);
 useEffect(()=>{let alive=true;setData(null);setError('');fetch(`/api/votes?memberId=${encodeURIComponent(member.id)}`).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error||'Voting records could not be loaded.');if(alive)setData(d);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[member.id,revision,retry]);
 if(error)return <div className="empty">{error}<Button variant="outline" onClick={()=>setRetry(x=>x+1)}>Retry voting records</Button></div>;if(!data)return <p role="status">Loading source-linked roll-call history…</p>;
 const topics=[...new Set<string>(data.votes.map((v:any)=>v.topic))].sort(),rows=data.votes.filter((v:any)=>(year==='all'||String(v.year)===year)&&(topic==='all'||v.topic===topic)&&`${v.title} ${v.bill?.label??''} ${v.question}`.toLowerCase().includes(query.toLowerCase()));
 const tree=new Map<string,Map<number,Map<string,any[]>>>();for(const v of rows){if(!tree.has(v.topic))tree.set(v.topic,new Map());const years=tree.get(v.topic)!;if(!years.has(v.year))years.set(v.year,new Map());const bills=years.get(v.year)!,key=v.bill?.key??v.id;if(!bills.has(key))bills.set(key,[]);bills.get(key)!.push(v);}
 const final=rows.filter((v:any)=>v.stage==='Passage / final agreement'),supported=new Set(final.filter((v:any)=>yes(v.position)).map((v:any)=>v.bill?.key??v.id)),opposed=new Set(final.filter((v:any)=>no(v.position)).map((v:any)=>v.bill?.key??v.id));
 return <section className="voting-history"><h2>Voting history · 2020–2026</h2><p>Topic first, then year, then bill. Each consolidated entry preserves every recorded vote in this view.</p><p className="note">Coverage begins in 2020 or the member’s first recorded congressional vote in that window. Official House/Senate records are supplemented by UCLA’s Voteview exports. Voice votes have no individual roll call. “Not Voting” is not a vote against a bill. Procedural and amendment votes are not treated as support for final passage.</p><div className="analysis-controls"><label className="analysis-choice"><span>Topic</span><Select value={topic} onValueChange={setTopic}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All topics</SelectItem>{topics.map(t=><SelectItem value={t} key={t}>{t}</SelectItem>)}</SelectContent></Select></label><label className="analysis-choice"><span>Year</span><Select value={year} onValueChange={setYear}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All years</SelectItem>{[2026,2025,2024,2023,2022,2021,2020].map(y=><SelectItem key={y} value={String(y)}>{y}</SelectItem>)}</SelectContent></Select></label><label className="analysis-choice"><span>Search bills and vote questions</span><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bill number or words in the title"/></label></div><div className="vote-summary"><strong>{rows.length}</strong> recorded votes · <strong>{supported.size}</strong> bills with a yes on passage/final agreement · <strong>{opposed.size}</strong> with a no</div><p className="note">A bill may appear in both counts if the member voted differently at different stages or on different versions. Counts describe recorded actions, not an inferred policy position.</p>
 {!rows.length&&<p className="empty">No recorded votes match this view.</p>}{[...tree.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([name,years])=><details className="vote-topic" key={name}><summary>{name}<span>{[...years.values()].reduce((n,b)=>n+[...b.values()].reduce((s,vs)=>s+vs.length,0),0)} votes</span></summary>{[...years.entries()].sort(([a],[b])=>b-a).map(([y,bills])=><section className="vote-year" key={y}><h3>{y} <small>{bills.size} consolidated items</small></h3><p className="year-summary">{(()=>{const all=[...bills.values()].flat(),p=all.filter(v=>v.stage==='Passage / final agreement'),y=new Set(p.filter(v=>yes(v.position)).map(v=>v.bill?.key??v.id)).size,n=new Set(p.filter(v=>no(v.position)).map(v=>v.bill?.key??v.id)).size;return `Final passage/agreement: yes on ${y} distinct measures; no on ${n}. ${all.filter(v=>v.stage==='Amendment').length} amendment votes and ${all.filter(v=>v.stage==='Procedure').length} procedural votes. ${all.filter(v=>v.position==='Not Voting').length} recorded as not voting.`;})()}</p>{[...bills.entries()].map(([key,vs])=>{const first=vs[0],pass=vs.filter(v=>v.stage==='Passage / final agreement'),ys=pass.filter(v=>yes(v.position)).length,ns=pass.filter(v=>no(v.position)).length;return <details className="bill-votes" key={key}><summary><span><b>{first.bill?.label??first.stage}</b> · {first.title}<small>{ys||ns?`Passage / final agreement: ${ys} yes, ${ns} no. `:'No yes/no final-passage vote in this group. '}{vs.length} recorded action{vs.length===1?'':'s'}.</small></span></summary><div className="bill-links">{first.bill&&<a href={first.bill.url} target="_blank" rel="noreferrer">Bill text & legislative history ↗</a>}{first.topicSource&&<a href={first.topicSource} target="_blank" rel="noreferrer">Topic source ↗</a>}</div>{vs.map(v=><article className="vote-action" key={v.id}><div><strong className={yes(v.position)?'vote-yes':no(v.position)?'vote-no':''}>{v.position}</strong><span>{v.date} · {v.chamber} roll {v.roll}</span></div><p>{v.question}</p><p className="note">{v.stage} · Chamber result: {v.result}</p><a href={v.source} target="_blank" rel="noreferrer">Verify recorded vote ↗</a><p className="note">Imported from <a href={v.dataSourceUrl??v.source} target="_blank" rel="noreferrer">{v.dataSource??'official roll call'}</a>{/speaker/i.test(v.question)&&v.dataSource?.startsWith('Voteview')?' · Speaker-election positions use Voteview’s yes/no coding; inspect the official record for the named candidate.':''}</p></article>)}</details>})}</section>)}</details>)}
 <details className="coverage"><summary>Import coverage and update dates</summary><p className="note">Topics use the bill’s congressional policy area, from GovInfo or the Voteview export. Years in the summary use the calendar date; coverage below uses legislative sessions. Omnibus bills remain under that broad area; votes are not attributed to every provision. Nominations and procedure are separate. Missing topic metadata is labeled unclassified. Sync latest records refreshes recent 2026 votes; archived years retain the import date shown below.</p>{data.coverage.map((c:any)=><p className="note" key={`${c.year}-${c.chamber}`}>{c.year} {c.chamber}: {c.imported} / {c.expected} roll calls imported{c.missingRolls?.length?` · ${c.missingRolls.length} omitted rolls (including quorum/vacated calls excluded by Voteview)`: ''} · through {c.through??'latest sync'} · imported {c.syncedAt?.slice(0,10)??data.syncedAt.slice(0,10)}</p>)}{data.failures?.length>0&&<p className="errors">{data.failures.length} source requests were unavailable. Coverage is incomplete.</p>}</details></section>;
}
