export const START_YEAR=2020;
export const xmlText=s=>String(s??'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]*>/g,'').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&').trim();
export const tag=(s,n)=>xmlText(s.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)</${n}>`))?.[1]);
const blocks=(s,n)=>[...s.matchAll(new RegExp(`<${n}(?:\\s[^>]*)?>[\\s\\S]*?</${n}>`,'g'))].map(m=>m[0]);
export function billIdentity(label,congress){const m=label.toLowerCase().replace(/[^a-z0-9]/g,'').match(/^(hr|s|hres|sres|hjres|sjres|hconres|sconres)(\d+)$/);if(!m)return null;const types={hr:'house-bill',s:'senate-bill',hres:'house-resolution',sres:'senate-resolution',hjres:'house-joint-resolution',sjres:'senate-joint-resolution',hconres:'house-concurrent-resolution',sconres:'senate-concurrent-resolution'};return {key:`${congress}-${m[1]}-${m[2]}`,congress:Number(congress),type:m[1],number:Number(m[2]),label:label.trim(),url:`https://www.congress.gov/bill/${congress}th-congress/${types[m[1]]}/${m[2]}`};}
export function stage(question){if(/cloture|proceed|recommit|table|waiv|previous question|adjourn|reconsider|point of order/i.test(question))return 'Procedure';if(/passage|pass the bill|on passing|suspend.*(?:pass|agree)|agree.*senate amendment|concur.*senate amendment|conference report|on agreeing to the resolution|^on the (?:joint )?resolution$/i.test(question))return 'Passage / final agreement';if(/amendment/i.test(question))return 'Amendment';if(/nomination/i.test(question))return 'Nomination';return 'Other recorded vote';}
export function parseVote(xml,chamber,year,roll,members){
 const congress=Number(tag(xml,'congress')),question=tag(xml,chamber==='House'?'vote-question':'question'),positions={};
 if(chamber==='House'){for(const b of blocks(xml,'recorded-vote')){const id=b.match(/name-id="([^"]+)"/)?.[1];if(members.some(m=>m.id===id))positions[id]=tag(b,'vote');}}
 else for(const b of blocks(xml,'member')){if(tag(b,'state')!=='FL')continue;const m=members.find(m=>m.chamber==='Senate'&&m.lastName.toLowerCase()===tag(b,'last_name').toLowerCase());if(m)positions[m.id]=tag(b,'vote_cast');}
 const rawDate=tag(xml,chamber==='House'?'action-date':'vote_date'),date=new Date(rawDate.split(',  ')[0]);
 const label=chamber==='House'?tag(xml,'legis-num'):tag(xml,'document_name');const bill=billIdentity(label,congress);
 const session=year%2?1:2;const source=chamber==='House'?`https://clerk.house.gov/Votes/${year}${roll}`:`https://www.senate.gov/legislative/LIS/roll_call_votes/vote${congress}${session}/vote_${congress}_${session}_${String(roll).padStart(5,'0')}.htm`;
 return {id:`${chamber}-${year}-${roll}`,chamber,year,roll,congress,date:Number.isNaN(+date)?rawDate:date.toISOString().slice(0,10),question,title:tag(xml,chamber==='House'?'vote-desc':'vote_title')||question,result:tag(xml,'vote-result')||tag(xml,'vote_result'),bill,stage:stage(question),positions,source,dataSource:chamber==='House'?'House Clerk':'U.S. Senate',dataSourceUrl:source,topic:bill?'Topic not yet classified':/^PN/i.test(label)||/nomination/i.test(question)?'Nominations':'Congressional procedure',topicSource:null};
}
export async function fetchText(url){const r=await fetch(url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`Official vote source returned HTTP ${r.status}`);return r.text();}
export async function voteIndex(chamber,year){if(chamber==='House'){const html=await fetchText(`https://clerk.house.gov/evs/${year}/index.asp`);const nums=[...html.matchAll(/rollnumber=(\d+)/gi)].map(m=>Number(m[1]));if(!nums.length)throw Error('House index contained no roll calls');return Array.from({length:Math.max(...nums)},(_,i)=>i+1);}const congress=Math.floor((year-1789)/2)+1,session=year%2?1:2;const xml=await fetchText(`https://www.senate.gov/legislative/LIS/roll_call_lists/vote_menu_${congress}_${session}.xml`);const rolls=blocks(xml,'vote').map(s=>Number(tag(s,'vote_number')));if(!rolls.length)throw Error('Senate index contained no roll calls');return rolls;}
export const voteXML=(chamber,year,roll)=>{const c=Math.floor((year-1789)/2)+1,s=year%2?1:2;return chamber==='House'?`https://clerk.house.gov/evs/${year}/roll${String(roll).padStart(3,'0')}.xml`:`https://www.senate.gov/legislative/LIS/roll_call_votes/vote${c}${s}/vote_${c}_${s}_${String(roll).padStart(5,'0')}.xml`;};
export async function billTopic(bill){const source=`https://www.govinfo.gov/bulkdata/BILLSTATUS/${bill.congress}/${bill.type}/BILLSTATUS-${bill.congress}${bill.type}${bill.number}.xml`;const xml=await fetchText(source);return {topic:tag(blocks(xml,'policyArea')[0]??'','name')||'Unclassified legislation',topicSource:source};}
